### ISSUE TITLE
question about immuno module

### ISSUE THREAD

**Issue by nicoleversetwo** [XSLiuLab/Seq2Neo#4]
Hi there, I'm just reading through the github and want to make sure I'm not misinterpreting the different modules. We have already used mutect2 and a few other somatic callers on our aligned files and have vcfs from each of these callers. Our main goal is to identify neoantigen burden across our cohort, and so I believe I can just use the immuno module to obtain the immunogenecity score? Is there an intermediate step I'm missing? Thank you!

**Comment by diaokx** [comment]
At present, Seq2Neo can only receive the original sequencing data and make predictions, and does not accept VCF files. I may update its functions soon, including running Seq2Neo without RNA-seq and running with VCF files (mutation calling is time-consuming).
